# Generated by Django 3.0.3 on 2020-02-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0002_auto_20200229_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videotitle',
            field=models.CharField(max_length=50),
        ),
    ]
